# roles/rh-base/vars/RedHat.yml
---
rhbase_systemd_services:
  - systemd-journald
  - systemd-tmpfiles-setup-dev
  - systemd-tmpfiles-setup

rhbase_dependencies:
  - firewalld
  - python3-libselinux
  - python3-libsemanage

rhbase_package_manager: dnf
rhbase_package_manager_configuration: /etc/dnf/dnf.conf

rhbase_updates_packages:
  - dnf-automatic
rhbase_updates_service: dnf-automatic.timer
rhbase_updates_config:
  - automatic.conf
