# roles/rhbase/tasks/config.yml
---

# This speeds up the Gathering Facts phase and several other situations where
# a DNS lookup is performed on the host name.
- name: Config | Ensure host name is in the hosts file
  lineinfile:
    dest: /etc/hosts
    state: present
    line: "{{ ansible_all_ipv4_addresses|last }} {{ ansible_hostname }} {{ ansible_hostname }}.{{ ansible_domain }}"
    regexp: "{{ ansible_hostname }}"
  when: rhbase_hosts_entry
  tags:
    - rhbase
    - config

- name: Config | Install dependency for dynamic MotD
  package:
    name: 'figlet'
    state: present
  when: rhbase_dynamic_motd
  tags:
    - rhbase
    - config

- name: Config | Install script generating dynamic MotD
  copy:
    src: dynamic-motd.sh
    dest: /etc/profile.d/dynamic-motd.sh
    owner: root
    group: root
    mode: 0644
  when: rhbase_dynamic_motd
  tags:
    - rhbase
    - config

# Workaround for bug https://bugs.centos.org/view.php?id=7407
# NetworkManager by default manages firewall zones, which overrides rules you
# add with --permanent.

- name: Config | Check if ifup-eth script overrides firewall zone
  shell: 'grep "Inform firewall which network zone" /etc/sysconfig/network-scripts/ifup-eth'
  register: ifup_eth_match
  when: not rhbase_override_firewalld_zones
  changed_when: false
  failed_when: false
  tags:
    - rhbase
    - config

- name: Config | Don’t override firewall zone in ifup-eth script
  shell: "sed -i -e '/Inform firewall which network zone/,+4d' /etc/sysconfig/network-scripts/ifup-eth"
  when: not rhbase_override_firewalld_zones and ifup_eth_match.stdout|length>0
  tags:
    - rhbase
    - config

- name: Config | Check if ifup-post script overrides firewall zone
  shell: 'grep "Inform firewall which network zone" /etc/sysconfig/network-scripts/ifup-post'
  register: ifup_post_match
  when: not rhbase_override_firewalld_zones
  changed_when: false
  failed_when: false
  tags:
    - rhbase
    - config

- name: Config | Don’t override firewall zone in ifup-post script
  shell: "sed -i -e '/Inform firewall which network zone/,+4d' /etc/sysconfig/network-scripts/ifup-post"
  when: not rhbase_override_firewalld_zones and ifup_post_match.stdout|length>0
  tags:
    - rhbase
    - config

- name: Config | Set the TZ environment variable
  template:
    src: etc_profile.d_localtime.j2
    dest: /etc/profile.d/localtime.sh
  tags:
    - rhbase
    - config

- name: Config | Set protocol version for SSH
  lineinfile:
    dest: /etc/ssh/sshd_config
    state: present
    create: true
    regexp: '^Protocol'
    line: "Protocol {{ rhbase_ssh_protocol_version }}"
  notify: restart sshd
  tags:
    - rhbase
    - config

- name: Config | Set PermitEmptyPasswords
  lineinfile:
    dest: /etc/ssh/sshd_config
    state: present
    create: true
    regexp: '^PermitEmptyPasswords'
    insertafter: '^#PermitEmptyPasswords'
    line: "PermitEmptyPasswords {{ rhbase_ssh_permitemptypasswords }}"
  notify: restart sshd
  tags:
    - rhbase
    - config

- name: Config | Set IgnoreRhosts
  lineinfile:
    dest: /etc/ssh/sshd_config
    state: present
    create: true
    regexp: '^IgnoreRhosts'
    insertafter: '^#IgnoreRhosts'
    line: "IgnoreRhosts {{ rhbase_ssh_ignorerhosts }}"
  notify: restart sshd
  tags:
    - rhbase
    - config

- name: Config | Set HostbasedAuthentication
  lineinfile:
    dest: /etc/ssh/sshd_config
    state: present
    create: true
    regexp: '^HostbasedAuthentication'
    insertafter: '^#HostbasedAuthentication'
    line: "HostbasedAuthentication {{ rhbase_ssh_hostbasedauthentication }}"
  notify: restart sshd
  tags:
    - rhbase
    - config

- name: Config | Set RhostsRSAAuthentication
  lineinfile:
    dest: /etc/ssh/sshd_config
    state: present
    create: true
    regexp: '^RhostsRSAAuthentication'
    insertafter: '^#RhostsRSAAuthentication'
    line: "RhostsRSAAuthentication {{ rhbase_ssh_rhostsrsaauthentication }}"
  notify: restart sshd
  tags:
    - rhbase
    - config


#- name: installeer de postgresql database (dit kan maar 1 keer uitgevoerd worden)
#  command:
#    cmd: postgresql-setup initdb
  #  cmd: $groepie=defined
#    creates: /var/lib/pgsql/data;
#  when: bar is undefined
#  notify: restart postgresql


#- name: Ensure postgresql is enabled en started
#  service:
#    name: postgresql
#    state: started
#    enabled: true
#  tags: httpd
#  become_user: postgresql

#- name: mappen maken virtual hosts sites available
#  file:
#    path: /etc/nginx/sites-available
#    state: directory
#    owner: santi
#    group: wheel
#    mode: 755

#- name: mappen maken virtual hosts sites available
#  file:
#    path: /etc/nginx/sites-enabled
#    state: directory
#    owner: santi
#    group: wheel
#    mode: 755

- name: overwrite config erop zetten
  template:
    src: files/nginx.conf
    dest: /etc/nginx/
    owner: santi
    group: wheel
    mode: 0755

#- name: symbolische link maken tussen config file sites-available en enabled (kan maar 1 keer uitvoeren)
#  shell:
#    cmd:  ln -s /etc/nginx/sites-available/corona2002.local.conf /etc/nginx/sites-enabled/

- name: zet default pagina klaar
  template:
    src: files/index.html
    dest: /var/www/corona2002.local/html/
    owner: santi
    group: wheel
    mode: 0755

- name: directory maken voor SSL
  file:
    path: /etc/nginx/ssl
    state: directory
    owner: santi
    group: wheel
    mode: 0755

- name: key klaarzetten SSL
  template:
    src: files/example.key
    dest: /etc/nginx/ssl
    owner: santi
    group: wheel
    mode: 0755

- name: certificate klaarzetten SSL
  template:
    src: files/example.crt
    dest: /etc/nginx/ssl
    owner: santi
    group: wheel
    mode: 0755

#- name: postgres nieuwe user maken
#  command:
#    cmd: createuser -P 



# onderstaand commando moet nog afgewerkt worden namelijk waar de lijn moet komen te staan, toch niet hij komt er gewoon vanonder bij
#- name: lijn toevoegen aan de config file om virtualhost config toe te voegen
#  lineinfile:
#    dest: /etc/nginx/nginx.conf
#    state: present
#    insertafter: 'include /etc/nginx/conf.d/*.conf;'
#    line: include /etc/nginx/sites-enabled/*.conf; 
#    owner: santi
#    group: wheel
#    mode: 755

# volgens mij is onderstaand niet op zijn juiste plaats maar moet dit in site
# enabled of site available






  #notify: restart_


#- name: include de virtual host configuratie
#  lineinfile:





#- name: start de database
#  shell:
#    cmd: /usr/bin/pg_ctl -D /var/lib/pgsql/data -l logfile start
#ag  become_user: postgres





    
