---
galaxy_info:
  author: Santi Meremans
  description: >-
    Ansible role for basic setup of a nginxwebserver with ssl wordpress and postgresql
  license: BSD
  min_ansible_version: 2.9
  platforms:
    - name: EL
      versions:
        - 7
        - 8
    - name: Fedora
      versions:
        - 32
  galaxy_tags:
    - system
dependencies: []
